# Amorphous Flow Matching Model Configuration
# 非晶碳 Flow Matching 模型配置

_target_: diffcsp.pl_modules.amorphous_flow_module.AmorphousFlowModule

# ============================================================================
# Model Selection (动态模型切换)
# ============================================================================
# Options: 'nequip' (默认), 'egnn', 'schnet'
# - nequip: E(3) 等变，最高精度，需要 e3nn
# - egnn: E(n) 等变，平衡速度与精度
# - schnet: 最快，非等变
model_type: nequip

# ============================================================================
# Model Configuration (模型特定配置)
# ============================================================================
# 通用配置会自动添加，这里只写模型特定参数
model_config:
  # NequIP 特定参数
  irreps_hidden: '64x0e + 32x1e + 32x2e'
  num_convs: 4
  radial_neurons: [16, 64]  # 第一个值必须与 edge_num_basis (16) 匹配
  num_neighbors: 12
  node_dim: 8
  edge_num_basis: 16
  
  # 如果使用 EGNN，取消注释:
  # hidden_dim: 256
  # n_layers: 4
  # attention: true
  
  # 如果使用 SchNet，取消注释:
  # hidden_dim: 256
  # n_interactions: 5
  # num_filters: 128

# ============================================================================
# Common Model Parameters (通用模型参数)
# ============================================================================
cutoff: 5.0
time_embed_dim: 32
cond_embed_dim: 32

# 条件范围 (log10 冷却速率)
cond_min_value: 1.3    # log10(20) ≈ 1.30
cond_max_value: 4.0    # log10(10000) = 4.0

# ============================================================================
# Training Configuration (训练配置)
# ============================================================================
# 盒子尺寸
box_size: [12.0, 12.0, 20.0]

# 2D 结构 (z = 0)
is_2d: true

# 先验分布
prior: uniform  # 'uniform' 或 'gaussian'

# 条件生成
use_condition: true

# ============================================================================
# Optimizer Configuration (优化器配置)
# ============================================================================
learning_rate: 1e-4
weight_decay: 0.0

# 学习率调度器
lr_scheduler: cosine_warmup  # 'cosine_warmup', 'step', null
lr_scheduler_params:
  warmup_epochs: 10
  min_lr: 1e-6

# EMA (指数移动平均)
ema_decay: 0.999

# ============================================================================
# ODE Sampling Configuration (采样配置)
# ============================================================================
# 这些参数用于 sample() 方法
ode_solver: euler  # 'euler', 'rk4', 'dopri5'
ode_steps: 100
