# Amorphous Flow Matching with SchNet Backend
# SchNet 后端配置 (最快，非等变)

_target_: diffcsp.pl_modules.amorphous_flow_module.AmorphousFlowModule

# Model Selection
model_type: schnet

# SchNet Configuration
model_config:
  hidden_dim: 256
  n_interactions: 5
  num_filters: 128
  rbf_type: gaussian
  num_rbf: 64

# Common Parameters
cutoff: 5.0
time_embed_dim: 32
cond_embed_dim: 32
cond_min_value: 1.3
cond_max_value: 4.0

# Training Configuration
box_size: [12.0, 12.0, 20.0]
is_2d: true
prior: uniform
use_condition: true

# Optimizer
learning_rate: 1e-4
weight_decay: 0.0
lr_scheduler: cosine_warmup
lr_scheduler_params:
  warmup_epochs: 10
  min_lr: 1e-6
ema_decay: 0.999
